# Generated by Django 5.0.6 on 2024-07-25 14:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageThree',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction_text', models.TextField(blank=True, null=True)),
                ('section_one_title', models.CharField(blank=True, max_length=256, null=True)),
                ('section_one_body', wagtail.fields.RichTextField(blank=True, null=True)),
                ('section_one_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_one_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('section_one_gallery', models.ForeignKey(blank=True, help_text='Select the image collection for this gallery.', limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageTwo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField()),
                ('section_one_body_left', wagtail.fields.RichTextField()),
                ('section_one_body_right', wagtail.fields.RichTextField()),
                ('section_one_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_two_text', models.TextField()),
                ('section_two_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_three_title', models.CharField(max_length=255)),
                ('section_three_body', wagtail.fields.RichTextField()),
                ('section_three_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_four_title', models.CharField(max_length=255)),
                ('section_four_body', wagtail.fields.RichTextField()),
                ('section_four_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_five_title', models.CharField(max_length=255)),
                ('section_five_body', wagtail.fields.RichTextField()),
                ('section_five_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_six_title', models.CharField(max_length=255)),
                ('section_six_body', wagtail.fields.RichTextField()),
                ('section_six_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_seven_text', models.CharField(max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_five_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('section_five_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_four_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('section_four_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_one_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('section_six_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('section_six_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_three_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('section_three_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_two_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
