# Generated by Django 5.0.6 on 2024-07-20 11:02

import django.db.models.deletion
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction_title', models.CharField(default='Accommodation', help_text='Title displayed above the introductory text', max_length=255)),
                ('introduction_text', wagtail.fields.RichTextField(help_text='Introductory text about the accommodation options')),
                ('maximum_capacity', models.PositiveIntegerField(default=26, help_text='Maximum number of guests allowed')),
                ('capacity_note', models.CharField(blank=True, help_text='Additional note about capacity, e.g., infants not included', max_length=255)),
                ('feature_1_title', models.CharField(default='Feature 1 Title', help_text='Title of the first accommodation feature', max_length=255)),
                ('feature_1_description', wagtail.fields.RichTextField(help_text='Description of the first accommodation feature')),
                ('feature_2_title', models.CharField(default='Feature 2 Title', help_text='Title of the second accommodation feature', max_length=255)),
                ('feature_2_description', wagtail.fields.RichTextField(help_text='Description of the second accommodation feature')),
                ('cta_button_text', models.CharField(default='Prices & Availability', help_text='Text for the call to action button', max_length=255)),
                ('cta_button_link', models.URLField(blank=True, help_text='URL where the button should lead')),
                ('gallery_images', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='Images to display in the gallery below the call to action.')),
                ('classic_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
                ('deluxe_suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
                ('family_suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
                ('upper_level_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
