# Generated by Django 5.0.6 on 2024-07-20 12:40

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='image',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='family_suite_image_gallery', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='AccomodationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction_title', models.CharField(blank=True, default='Accommodation', help_text='Title displayed above the introductory text', max_length=255, null=True)),
                ('introduction_text', wagtail.fields.RichTextField(blank=True, help_text='Introductory text about the accommodation options', null=True)),
                ('feature_description_one', wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the accommodation feature')), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Description of the first accommodation feature'))]))], blank=True, null=True)),
                ('feature_description_two', wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the accommodation feature')), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Description of the first accommodation feature'))]))], blank=True, null=True)),
                ('cta_button_text', models.CharField(blank=True, default='Prices & Availability', help_text='Text for the call to action button', max_length=255, null=True)),
                ('look_around_title', models.CharField(blank=True, help_text='Title for Take a look around section', max_length=255, null=True)),
                ('look_around_text', wagtail.fields.RichTextField(blank=True, help_text='Text for Take a look around section')),
                ('cta_button_text_two', models.CharField(blank=True, default='Prices & Availability', help_text='Text for the call to action button', max_length=255, null=True)),
                ('classic_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
                ('cta_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('cta_button_link_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('deluxe_suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
                ('family_suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image_gallery_one', models.ManyToManyField(blank=True, related_name='gallery_one', to='wagtailimages.image')),
                ('image_gallery_two', models.ManyToManyField(blank=True, related_name='gallery_two', to='wagtailimages.image')),
                ('upper_level_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='AccommodationPage',
        ),
    ]
