# Generated by Django 5.0.6 on 2024-07-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0004_rename_collection_accomodationpage_look_around_gallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodationpage',
            old_name='look_around_gallery',
            new_name='image_collection_one',
        ),
    ]
