# Generated by Django 5.0.6 on 2024-07-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0007_alter_accomodationpage_floor_layout_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationpage',
            name='cta_button_link_two',
        ),
        migrations.RemoveField(
            model_name='accomodationpage',
            name='floor_layout_doc',
        ),
    ]
