# Generated by Django 5.0.6 on 2024-07-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0008_remove_accomodationpage_cta_button_link_two_and_more'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodationpage',
            name='floor_layout_doc',
            field=models.ForeignKey(blank=True, help_text='Select the floor layout document.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
    ]
