# Generated by Django 5.0.6 on 2024-07-21 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0009_accomodationpage_floor_layout_doc'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='images',
        ),
        migrations.AddField(
            model_name='accomodationpage',
            name='image_collection_two',
            field=models.ForeignKey(blank=True, help_text='Select the image collection for this gallery.', limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Select the image collection for this gallery.', limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='accomodationpage',
            name='cta_button_text_two',
            field=models.CharField(blank=True, default='DOWNLOAD FLOOR LAYOUT', help_text='Text for this button', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accomodationpage',
            name='floor_layout_doc',
            field=models.ForeignKey(blank=True, help_text='Select the floor layout document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='accomodationpage',
            name='image_collection_one',
            field=models.ForeignKey(blank=True, help_text='Select the image collection for this gallery.', limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='accomodationpage',
            name='look_around_title',
            field=models.CharField(blank=True, default='Take a look around...', help_text='Title for Take a look around section', max_length=255, null=True),
        ),
    ]
