# Generated by Django 5.0.6 on 2024-07-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0010_remove_roomtype_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodationpage',
            name='retreat_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accomodation.roomtype'),
        ),
    ]
