# Generated by Django 5.0.6 on 2024-07-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0011_accomodationpage_retreat_facility'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='cta_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='cta_button_text',
            field=models.CharField(blank=True, default='REQUEST TO BOOK', help_text='Text for the call to action button', max_length=255, null=True),
        ),
    ]
