# Generated by Django 5.0.6 on 2024-07-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0012_roomtype_cta_button_link_roomtype_cta_button_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='cta_button_link',
            new_name='cta_link',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='cta_button_text',
            new_name='cta_text',
        ),
    ]
