# Generated by Django 5.0.6 on 2024-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0014_pricing_roomnumber_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='room_type',
        ),
        migrations.AddField(
            model_name='availability',
            name='room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accomodation.roomnumber'),
        ),
    ]
