# Generated by Django 5.0.6 on 2024-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0018_pagetwo_delete_groupspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetwo',
            name='section_seven_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
