# Generated by Django 5.0.6 on 2024-07-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0019_pagetwo_section_seven_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetwo',
            name='section_five_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagetwo',
            name='section_four_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagetwo',
            name='section_one_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagetwo',
            name='section_six_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagetwo',
            name='section_three_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagetwo',
            name='section_two_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
