# Generated by Django 5.0.6 on 2024-07-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0020_alter_pagetwo_section_five_cta_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageTwo',
        ),
    ]
