# Generated by Django 5.0.6 on 2024-07-25 14:10

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('carousel', wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True)),
                ('introduction_title', models.CharField(blank=True, max_length=255, null=True)),
                ('introduction_subheading', models.TextField(blank=True, null=True)),
                ('introduction_cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('featured_section_one', wagtail.fields.StreamField([('post_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('subheading', wagtail.blocks.TextBlock())]))], blank=True, null=True)),
                ('featured_section_two', wagtail.fields.StreamField([('post_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('subheading', wagtail.blocks.TextBlock())]))], blank=True, null=True)),
                ('section_three', models.CharField(blank=True, max_length=255, null=True)),
                ('accomodation_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('accomodation_section_subheading', models.TextField(blank=True, null=True)),
                ('accomodation_section_paragraph', models.TextField(blank=True, null=True)),
                ('location_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('location_section_subheading', models.TextField(blank=True, null=True)),
                ('services_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('styled_link_text', models.CharField(blank=True, max_length=256, null=True)),
                ('accommodation_section_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('accomodation_section_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('introduction_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('styled_link_text_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AccomodationFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_features', to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='IconLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(choices=[('e_fas_swimmer', 'Swimmer'), ('e_fas_biking', 'Biking'), ('e_fas_car_alt', 'Car'), ('e_fas_bus', 'Bus'), ('e_fas_glass_cheers', 'Glass Cheers'), ('e_fas_atom', 'Atom')], max_length=255)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_links', to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('cta_text', models.CharField(max_length=255, null=True)),
                ('cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.homepage')),
            ],
        ),
    ]
