# Generated by Django 5.0.6 on 2024-07-19 13:06

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_accommodations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='accommodations',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='accommodations_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='additional_services',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='additional_services_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='location_image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='location_image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='location_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.CharBlock()), ('cta_text', wagtail.blocks.CharBlock()), ('cta_link', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
