# Generated by Django 5.0.6 on 2024-07-19 13:20

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_accommodations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('cta_text', wagtail.blocks.CharBlock()), ('cta_link', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
