# Generated by Django 5.0.6 on 2024-07-20 04:55

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_introduction_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section_one',
            field=wagtail.fields.StreamField([('post_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('subheading', wagtail.blocks.TextBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_two',
            field=wagtail.fields.StreamField([('post_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('subheading', wagtail.blocks.TextBlock())]))], blank=True, null=True),
        ),
    ]
