# Generated by Django 5.0.6 on 2024-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_featured_section_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
