# Generated by Django 5.0.6 on 2024-07-20 05:49

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_section_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='accomodation_section_body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.CharBlock(required=False)), ('bullets', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='accomodation_section_images',
            field=wagtail.fields.StreamField([('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='accomodation_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
