# Generated by Django 5.0.6 on 2024-07-20 06:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_accomodation_section_body_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='accomodation_section_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='accomodation_section_images',
        ),
        migrations.AddField(
            model_name='homepage',
            name='accomodation_section_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='accomodation_section_subheading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccomodationFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_features', to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_images', to='home.homepage')),
            ],
        ),
    ]
