# Generated by Django 5.0.6 on 2024-07-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_iconlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iconlink',
            old_name='cta_link',
            new_name='link',
        ),
        migrations.AddField(
            model_name='iconlink',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
