# Generated by Django 5.0.6 on 2024-07-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_navigationmenu_navigationmenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.navigationmenu'),
        ),
    ]
