# Generated by Django 5.0.6 on 2024-07-22 12:40

import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_navigationmenuitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='is_title',
        ),
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_menu_items', to='base.navigationmenu'),
        ),
    ]
