# Generated by Django 5.0.6 on 2024-07-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_navigationmenuitem_is_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationmenuitem',
            old_name='title',
            new_name='link_title',
        ),
    ]
