# Generated by Django 5.0.6 on 2024-07-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_title_navigationmenuitem_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationmenu',
            name='slug',
        ),
    ]
