# Generated by Django 5.0.6 on 2024-07-22 12:51

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_navigationmenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
