# Generated by Django 5.0.6 on 2024-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_navigationmenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='show_submenu',
            field=models.BooleanField(default=True),
        ),
    ]
