# Generated by Django 5.0.6 on 2024-07-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostRetreat',
            new_name='HostRetreatPage',
        ),
        migrations.RenameModel(
            old_name='ReteatAccomodation',
            new_name='ReteatAccomodationPage',
        ),
    ]
